# Generated by Django 5.0.1 on 2024-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_glucosevalue_chart_gluco_user_id_e66e30_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosevalue',
            name='value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
