# Generated by Django 5.0.1 on 2024-04-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_alter_source_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosevalue',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.source'),
        ),
    ]
