# Generated by Django 5.0.1 on 2024-03-26 10:51

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_source_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='glucosevalue',
            name='chart_gluco_user_id_e66e30_idx',
        ),
        migrations.AddField(
            model_name='glucosevalue',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 10, 51, 55, 655661), editable=False),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='glucosevalue',
            index=models.Index(fields=['user', 'timestamp'], name='chart_gluco_user_id_7f5f4f_idx'),
        ),
    ]
