# Generated by Django 5.0.1 on 2024-03-27 10:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_remove_glucosevalue_chart_gluco_user_id_e66e30_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='api_key',
            new_name='token',
        ),
        migrations.AddField(
            model_name='source',
            name='email',
            field=models.CharField(default='test@email.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='patient_id',
            field=models.CharField(default='test123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='sensor_start',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
