# Generated by Django 5.0.1 on 2024-03-08 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_glucosevalue_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='glucosevalue',
            index=models.Index(fields=['user', 'time_of_reading'], name='chart_gluco_user_id_e66e30_idx'),
        ),
    ]
